version: 0.2

phases:
  pre_build:
    commands:
    - echo "Starting pre-build phase..."
    - echo "Logging in to Amazon ECR..."
    - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 975050121873.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
    - echo "Starting build phase..."
    - echo "Building the Docker image..."
    - docker build -t beniwal-api .
    - echo "Tagging the Docker image..."
    - docker tag beniwal-api:latest 975050121873.dkr.ecr.us-east-1.amazonaws.com/beniwal-api:latest
  post_build:
    commands:
    - echo "Starting post-build phase..."
    - echo "Pushing the Docker image to Amazon ECR..."
    - docker push 975050121873.dkr.ecr.us-east-1.amazonaws.com/beniwal-api:latest
    - echo "Build and push completed."

artifacts:
  files:
  - - imagedefinitions.json
